"""link summary field

Revision ID: af3591657f3d
Revises: ef4cdd57d5e1
Create Date: 2025-04-05 11:04:40.840204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'af3591657f3d'
down_revision: Union[str, None] = 'ef4cdd57d5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'summary')
    # ### end Alembic commands ###
