"""link read

Revision ID: 4c90cbaaee7d
Revises: f773bac176c0
Create Date: 2025-01-30 21:46:53.593999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c90cbaaee7d'
down_revision: Union[str, None] = 'f773bac176c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add read column as nullable first
    op.add_column('link', sa.Column('read', sa.Boolean(), nullable=True))
    
    # Update existing rows to have read=False
    op.execute("UPDATE link SET read = FALSE")
    
    # Make the column non-nullable
    op.alter_column('link', 'read', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'read')
    # ### end Alembic commands ###
